language: node_js
node_js:
  - "6"
dist: trusty

cache:
  directories:
    - "node_modules"

script:
  - npm run build  # Build the SPA

deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
  target-branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard.
  on:
    all_branches: true
  local_dir: dist
  fqdn: ubacm.org
